### ISSUE TITLE
Server "Core" + strategies + Kind of: etc...

### ISSUE THREAD

**Issue by petr-fischer** [pharo-ide/Seamless#16]
I loaded "Core" package for "server side" image and want to use:
```
network transferByValue: (Kind of: Collection).
```
But for "Kind of:", StateSpecs-DSL* package is needed.
Isn't there a missing dependency in "Core" server package? Or you don't want StateSpecs in Core?

**Comment by dionisiydk** [comment]
Idea to not introduce this dependency because it is just about single message.
Argument in your example is any object which understand #matches: . So you can implement your own criteria. And if you want full power of what StateSpecs provide then load it:
```Smalltalk
Metacello new
  baseline: 'StateSpecs';
  repository: 'github://dionisiydk/StateSpecs';
  load
```

**Comment by dionisiydk** [comment]
And StateSpecs is used for tests in Seamless and dependencies. So in Pharo6 it will be available with full installation

**Comment by petr-fischer** [comment]
Thanks for clarification.
