### ISSUE TITLE
All test pass on Pharo 7 except for 3  that raise errors

### ISSUE THREAD

**Issue by bouraqadi** [pharo-ide/Seamless#20]
testExecutingDoItWithGlobalReferenceOnRemoteObjectByRemoteCompiler
testExecutingDoItWithInstVarAssignmentOnRemoteObject
testExecutingDoItWithInstVarAssignmentOnRemoteObjectWhenRequestorIsSpecified

All raise exception TestFailedByForkedProcess

**Comment by dionisiydk** [comment]
fixed
