### ISSUE TITLE
Unable to install on Pharo 9

### ISSUE THREAD

**Issue by psvensson** [pharo-ide/Seamless#46]
Using the instructions, I get a warning that a package depends on OCClassScope, not sure if this breaks something or not, just wanted to check.

![image](https://user-images.githubusercontent.com/39554/122246633-00abb980-cec7-11eb-9f39-39eaf946f241.png)

**Comment by MarcusDenker** [comment]
We are working on it! I hope to commit a working version later today (just one test is failing...)

**Comment by psvensson** [comment]
OK, wonderful. All of this is just awesome, by the way.

**Comment by MarcusDenker** [comment]
Sadly it is hard to find the time that is needed to push it forward...

**Comment by MarcusDenker** [comment]
We have a PR that should make it loadable (with green tests): https://github.com/pharo-ide/Seamless/pull/47

But: the tools need to now be ported to use it. Which means this, in itself, is not that useful.

**Comment by psvensson** [comment]
OK, that sounds good. I'll see if I can help out a bit over the summer, when I have more time myself. Which parts do you think would be the best to start on if I wanted to contribute?

**Comment by MarcusDenker** [comment]
On our TODO next is to work on the playground.

Maybe the easiest next is the inspector: this is I think mostly the special inspector, that is look at what we need to do to have
SeamlessProxy>>#gtInspectorRawIn: for the newtools inspector.
