### ISSUE TITLE
Can't load Seamless in Pharo 5

### ISSUE THREAD

**Issue by petr-fischer** [pharo-ide/Seamless#9]
Last line in log after load attempt:

`...FAILED->Seamless-Pharo5Support`

Exception dialog with message:
`Could not resolve: Seamless-Pharo5Support [Seamless-Pharo5Support] in C:\Users\pfischer\Documents\Smalltalk\Pharo5.0\package-cache github://dionisiydk/Seamless:master`

Is Pharo 5 supported?

**Comment by dionisiydk** [comment]
I made new version with missing support package for Pharo5. 
But it is has some problems with tests and inspector. It is not related to core functionality. So you can use it without tests. 
Also remote inspector can be fixed with deprecated pragma message #selector

**Comment by dionisiydk** [comment]
And I made another fix for Pharo5.
Look at new release for details. Remote inspector is working with it
